import '../models/notification_item.dart';

class MockDataGenerator {
  static List<NotificationItem> generateMockNotifications() {
    final now = DateTime.now();

    return [
      NotificationItem(
        id: 'notif_001',
        notificationId: 'nid_9812471',
        deduplicationHash: 'a7b9c1d3e5f72890',
        packageName: 'com.whatsapp',
        key: '0|com.whatsapp|1001|null|10001',
        title: 'Sarah Connor',
        text: 'Hey! The new Flutter application build is looking incredible. Are we deploying today?',
        subText: '2 new messages',
        bigText: 'Sarah Connor: Hey! The new Flutter application build is looking incredible. Are we deploying today?\nAlex: Yes, ready after QA check.',
        category: 'msg',
        deviceTimestamp: now.subtract(const Duration(minutes: 4)),
        receivedAt: now.subtract(const Duration(minutes: 4)),
        firstReceivedAt: now.subtract(const Duration(minutes: 4)),
        lastReceivedAt: now.subtract(const Duration(minutes: 4)),
        rawPayload: {
          'packageName': 'com.whatsapp',
          'title': 'Sarah Connor',
          'text': 'Hey! The new Flutter application build is looking incredible.',
          'subText': '2 new messages',
          'time': now.subtract(const Duration(minutes: 4)).millisecondsSinceEpoch,
          'category': 'msg',
          'channelId': 'chat_messages_v2',
          'postTime': now.subtract(const Duration(minutes: 4)).millisecondsSinceEpoch
        },
        requestId: 'req_wsp_8912',
        source: 'Android Notification Listener',
        processingStatus: ProcessingStatusType.processed,
        deliveryAttempts: 1,
        ipHash: 'ip_e41a99bc',
        userAgent: 'Android 14 (API 34) Pixel 8 Pro',
        isPinned: true,
      ),
      NotificationItem(
        id: 'notif_002',
        notificationId: 'nid_9812472',
        deduplicationHash: 'b2c4d6e8f0123456',
        packageName: 'com.chase.sig.android',
        key: '0|com.chase.sig.android|2002|null|10002',
        title: 'Security Alert: Debit Card Purchase',
        text: '\$142.50 spent at Apple Store Online (Card ending *4892)',
        subText: 'Fraud Protection',
        bigText: 'Your Chase Visa card ending in 4892 was charged \$142.50 at Apple Store Online on Sep 16, 2026. If you did not authorize this transaction, lock your card immediately in the mobile app.',
        category: 'finance',
        deviceTimestamp: now.subtract(const Duration(minutes: 18)),
        receivedAt: now.subtract(const Duration(minutes: 18)),
        firstReceivedAt: now.subtract(const Duration(minutes: 18)),
        lastReceivedAt: now.subtract(const Duration(minutes: 18)),
        rawPayload: {
          'packageName': 'com.chase.sig.android',
          'title': 'Security Alert: Debit Card Purchase',
          'text': '\$142.50 spent at Apple Store Online',
          'amount': 142.50,
          'currency': 'USD',
          'merchant': 'Apple Store Online',
          'category': 'finance',
          'time': now.subtract(const Duration(minutes: 18)).millisecondsSinceEpoch
        },
        requestId: 'req_bank_7721',
        source: 'Android Push Webhook',
        processingStatus: ProcessingStatusType.processed,
        deliveryAttempts: 1,
        ipHash: 'ip_b77c1200',
        userAgent: 'Chase Mobile/24.9 Android',
        isPinned: true,
      ),
      NotificationItem(
        id: 'notif_003',
        notificationId: 'nid_9812473',
        deduplicationHash: 'c3d5e7f9a1b3c5d7',
        packageName: 'com.slack',
        key: '0|com.slack|3003|null|10003',
        title: '#devops-alerts',
        text: 'CRITICAL: Redis cluster memory usage hit 91% threshold on Node prod-db-03',
        subText: 'DevOps Workspace',
        bigText: 'Alert triggered by Prometheus Monitoring.\nHost: prod-db-03.us-east-1.internal\nMetric: redis_memory_used_ratio = 0.912\nAction required: Run eviction or scale memory limits.',
        category: 'security',
        deviceTimestamp: now.subtract(const Duration(minutes: 32)),
        receivedAt: now.subtract(const Duration(minutes: 32)),
        firstReceivedAt: now.subtract(const Duration(minutes: 35)),
        lastReceivedAt: now.subtract(const Duration(minutes: 32)),
        rawPayload: {
          'packageName': 'com.slack',
          'channel': '#devops-alerts',
          'severity': 'CRITICAL',
          'node': 'prod-db-03',
          'time': now.subtract(const Duration(minutes: 32)).millisecondsSinceEpoch
        },
        requestId: 'req_slk_0019',
        source: 'Prometheus Slack Gateway',
        processingStatus: ProcessingStatusType.received,
        deliveryAttempts: 2,
        ipHash: 'ip_99fa1212',
        userAgent: 'Slack-Android/24.08',
      ),
      NotificationItem(
        id: 'notif_004',
        notificationId: 'nid_9812474',
        deduplicationHash: 'c3d5e7f9a1b3c5d7', // intentional duplicate hash for demo
        packageName: 'com.slack',
        key: '0|com.slack|3003|null|10004',
        title: '#devops-alerts',
        text: 'CRITICAL: Redis cluster memory usage hit 91% threshold on Node prod-db-03',
        subText: 'DevOps Workspace',
        bigText: 'Alert triggered by Prometheus Monitoring.\nHost: prod-db-03.us-east-1.internal\nMetric: redis_memory_used_ratio = 0.912',
        category: 'security',
        deviceTimestamp: now.subtract(const Duration(minutes: 30)),
        receivedAt: now.subtract(const Duration(minutes: 30)),
        firstReceivedAt: now.subtract(const Duration(minutes: 35)),
        lastReceivedAt: now.subtract(const Duration(minutes: 30)),
        rawPayload: {
          'packageName': 'com.slack',
          'duplicateReason': 'identical_hash_within_5min',
          'time': now.subtract(const Duration(minutes: 30)).millisecondsSinceEpoch
        },
        requestId: 'req_slk_0020',
        source: 'Prometheus Slack Gateway',
        processingStatus: ProcessingStatusType.received,
        deliveryAttempts: 1,
        ipHash: 'ip_99fa1212',
        userAgent: 'Slack-Android/24.08',
        isDuplicate: true,
      ),
      NotificationItem(
        id: 'notif_005',
        notificationId: 'nid_9812475',
        deduplicationHash: 'd4e6f8a0b2c4d6e8',
        packageName: 'com.google.android.gm',
        key: '0|com.google.android.gm|4004|null|10005',
        title: 'GitHub Notifications',
        text: '[luxeenet/notsave] Pull Request #14 merged: Feature/NotificationDeduplication',
        subText: 'dev@company.com',
        bigText: 'Pull request #14 "Add deduplication hash index and TTL TTL index to mongodb" was merged into main by @senior-dev.',
        category: 'msg',
        deviceTimestamp: now.subtract(const Duration(hours: 1, minutes: 12)),
        receivedAt: now.subtract(const Duration(hours: 1, minutes: 12)),
        firstReceivedAt: now.subtract(const Duration(hours: 1, minutes: 12)),
        lastReceivedAt: now.subtract(const Duration(hours: 1, minutes: 12)),
        rawPayload: {
          'packageName': 'com.google.android.gm',
          'sender': 'notifications@github.com',
          'pr': 14,
          'repo': 'luxeenet/notsave',
          'time': now.subtract(const Duration(hours: 1, minutes: 12)).millisecondsSinceEpoch
        },
        requestId: 'req_gml_9921',
        source: 'Gmail Android Client',
        processingStatus: ProcessingStatusType.processed,
        deliveryAttempts: 1,
        ipHash: 'ip_77da8811',
        userAgent: 'Gmail/2026.08.15 Android',
      ),
      NotificationItem(
        id: 'notif_006',
        notificationId: 'nid_9812476',
        deduplicationHash: 'e5f7a9b1c3d5e7f9',
        packageName: 'com.ubercab.eats',
        key: '0|com.ubercab.eats|5005|null|10006',
        title: 'Courier is nearby! 🛵',
        text: 'Your order from Artisan Ramen & Bistro is arriving in 3 minutes.',
        subText: 'Order #7890',
        bigText: 'Driver Michael (Toyota Prius - Silver, License 7XYZ89) is 300 meters away. Please meet at front lobby.',
        category: 'custom',
        deviceTimestamp: now.subtract(const Duration(hours: 2, minutes: 5)),
        receivedAt: now.subtract(const Duration(hours: 2, minutes: 5)),
        firstReceivedAt: now.subtract(const Duration(hours: 2, minutes: 5)),
        lastReceivedAt: now.subtract(const Duration(hours: 2, minutes: 5)),
        rawPayload: {
          'packageName': 'com.ubercab.eats',
          'orderId': '7890',
          'driver': 'Michael',
          'eta': '3 mins',
          'time': now.subtract(const Duration(hours: 2, minutes: 5)).millisecondsSinceEpoch
        },
        requestId: 'req_ubr_4123',
        source: 'Uber Push Gateway',
        processingStatus: ProcessingStatusType.processed,
        deliveryAttempts: 1,
        ipHash: 'ip_11aa22bb',
        userAgent: 'UberEats/6.210 Android',
      ),
      NotificationItem(
        id: 'notif_007',
        notificationId: 'nid_9812477',
        deduplicationHash: 'f6a8b0c2d4e6f8a0',
        packageName: 'com.android.systemui',
        key: '0|com.android.systemui|6006|null|10007',
        title: 'System Software Update Ready',
        text: 'Android 15 Security Patch (Build AP3A.240905.015) is downloaded.',
        subText: 'System Service',
        bigText: 'Update size: 480 MB. Restart your device to apply system updates, stability fixes, and kernel security patches.',
        category: 'sys',
        deviceTimestamp: now.subtract(const Duration(hours: 3, minutes: 40)),
        receivedAt: now.subtract(const Duration(hours: 3, minutes: 40)),
        firstReceivedAt: now.subtract(const Duration(hours: 3, minutes: 40)),
        lastReceivedAt: now.subtract(const Duration(hours: 3, minutes: 40)),
        rawPayload: {
          'packageName': 'com.android.systemui',
          'buildId': 'AP3A.240905.015',
          'patchLevel': '2026-09-01',
          'category': 'sys',
          'time': now.subtract(const Duration(hours: 3, minutes: 40)).millisecondsSinceEpoch
        },
        requestId: 'req_sys_0001',
        source: 'SystemUI Listener',
        processingStatus: ProcessingStatusType.processed,
        deliveryAttempts: 1,
        ipHash: 'ip_localhost',
        userAgent: 'Android System Service',
      ),
      NotificationItem(
        id: 'notif_008',
        notificationId: 'nid_9812478',
        deduplicationHash: 'a1b2c3d4e5f67890',
        packageName: 'com.stripe.android',
        key: '0|com.stripe.android|7007|null|10008',
        title: 'Payout Failed: Invalid Webhook Endpoint',
        text: 'HTTP 500 error returned by customer endpoint https://api.client.com/webhooks',
        subText: 'Stripe Connect',
        bigText: 'Webhook attempt #3 failed with response code 500 Internal Server Error. Webhook event ID: evt_1P9xZ82eZvKYlo2C.',
        category: 'finance',
        deviceTimestamp: now.subtract(const Duration(hours: 5, minutes: 15)),
        receivedAt: now.subtract(const Duration(hours: 5, minutes: 15)),
        firstReceivedAt: now.subtract(const Duration(hours: 5, minutes: 15)),
        lastReceivedAt: now.subtract(const Duration(hours: 5, minutes: 15)),
        rawPayload: {
          'packageName': 'com.stripe.android',
          'eventId': 'evt_1P9xZ82eZvKYlo2C',
          'error': '500 Internal Server Error',
          'category': 'finance',
          'time': now.subtract(const Duration(hours: 5, minutes: 15)).millisecondsSinceEpoch
        },
        requestId: 'req_str_9981',
        source: 'Stripe Webhook Listener',
        processingStatus: ProcessingStatusType.failed,
        deliveryAttempts: 3,
        ipHash: 'ip_5421100',
        userAgent: 'Stripe-Hookshot/1.0',
      ),
      NotificationItem(
        id: 'notif_009',
        notificationId: 'nid_9812479',
        deduplicationHash: 'b3c4d5e6f7a89012',
        packageName: 'org.telegram.messenger',
        key: '0|org.telegram.messenger|8008|null|10009',
        title: 'Dev Channel 🚀',
        text: 'New release v2.4.0 published to NPM & Docker Hub!',
        subText: '14 channel subscribers',
        bigText: 'Changelog:\n- Added deduplication cache\n- Enhanced mongodb indices\n- Added OpenAPI swagger documentation UI',
        category: 'social',
        deviceTimestamp: now.subtract(const Duration(hours: 8)),
        receivedAt: now.subtract(const Duration(hours: 8)),
        firstReceivedAt: now.subtract(const Duration(hours: 8)),
        lastReceivedAt: now.subtract(const Duration(hours: 8)),
        rawPayload: {
          'packageName': 'org.telegram.messenger',
          'chatTitle': 'Dev Channel',
          'version': 'v2.4.0',
          'category': 'social',
          'time': now.subtract(const Duration(hours: 8)).millisecondsSinceEpoch
        },
        requestId: 'req_tg_7712',
        source: 'Telegram Client',
        processingStatus: ProcessingStatusType.processed,
        deliveryAttempts: 1,
        ipHash: 'ip_9912001',
        userAgent: 'Telegram Android 10.14',
      ),
    ];
  }
}
